# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: prednet

dependencies:
  - python=3.6
  - pip=19.0.3

  - pip:
    - keras==2.0.8
    - theano==1.0.4
    - tensorflow==1.8.0
    - tensorflow-gpu==1.8.0
    - hickle==3.4.3
    - matplotlib==3.0.3
    - seaborn==0.9.0
    - requests==2.21.0
    - bs4==0.0.1
    - sklearn
    - pandas==0.24.2
    - azureml-sdk==1.0.29
    - numpy==1.16.2
    - pylint # optional
    - pillow==6.0.0
    